editor_name: Multi
editor_adress: 116 rue Dalayrac - 94120 - Fontenay-sous-Bois / France
editor_tel: +33 83 65 84 91
editor_code: 822 968 699
provider_name: OVH
provider_adress: 2 rue Kellermann - 59100 Roubaix - France
provider_site: https://www.ovh.com/fr/support/documents_legaux/
